package com.example.spinner03


enum class Months(val holder: String) {
    ALL("모두"),
    JAN("1월"),
    FEB("2월"),
    MAR("3월"),
    APR("4월"),
    MAY("5월"),
    JUN("6월"),
    JUL("7월"),
    AUG("8월"),
    SEP("9월"),
    OCT("10월"),
    NOV("11월"),
    DEC("12월"),
}

data class SingerData(val imgRes: Int, val singer: String, val song: String, val featured: Months)

val singerDatas: Array<SingerData> = arrayOf(
    SingerData(R.drawable.album1, "장범준", "당신과는 천천히", Months.JAN),
    SingerData(R.drawable.album2, "태연", "사계", Months.JAN),
    SingerData(R.drawable.album3, "장범준", "노래방에서", Months.JAN),
    SingerData(R.drawable.album4, "백예린", "그건 아마 우리의 잘못은 아닐꺼야", Months.JAN),
    SingerData(R.drawable.album5, "ITZY", "달라달라", Months.JAN),
    SingerData(R.drawable.album6, "잔나비", "주저하는 연일들을 위해", Months.FEB),
    SingerData(R.drawable.album7, "엔플라잉", "옥탑방", Months.FEB),
    SingerData(R.drawable.album8, "에픽하이", "술이 달다", Months.FEB),
    SingerData(R.drawable.album9, "마마무", "고고베베", Months.FEB),
    SingerData(R.drawable.album10, "청하", "벌써 12시", Months.FEB),
    SingerData(R.drawable.album11, "우원재", "디어", Months.MAR),
    SingerData(R.drawable.album12, "사생활", "Film", Months.MAR),
    SingerData(R.drawable.album13, "여자", "ARTIST", Months.MAR),
    SingerData(R.drawable.album14, "OST", "Fresher", Months.MAR),
    SingerData(R.drawable.album15, "유엔젤보이스", "us", Months.MAR),
    SingerData(R.drawable.album16, "OST", "Crash", Months.APR),
    SingerData(R.drawable.album17, "대니", "COME", Months.APR),
    SingerData(R.drawable.album18, "마이", "Just", Months.APR),
    SingerData(R.drawable.album19, "마리슈", "날", Months.APR),
    SingerData(R.drawable.album20, "Film", "Prelude", Months.APR),
    SingerData(R.drawable.album21, "DEUL", "빙의", Months.MAY),
    SingerData(R.drawable.album22, "ARTIST", "숨", Months.MAY),
    SingerData(R.drawable.album23, "어나니머스아티스트", "Now", Months.MAY),
    SingerData(R.drawable.album24, "Than", "satan", Months.MAY),
    SingerData(R.drawable.album25, "Mac9", "예쁜날", Months.MAY),
    SingerData(R.drawable.album26, "us", "흔적", Months.JUN),
    SingerData(R.drawable.album27, "픽보이", "Too", Months.JUN),
    SingerData(R.drawable.album28, "And", "넌", Months.JUN),
    SingerData(R.drawable.album29, "In", "둘이", Months.JUN),
    SingerData(R.drawable.album30, "THRU", "Price", Months.JUN),
    SingerData(R.drawable.album31, "hu57la", "이게", Months.JUL),
    SingerData(R.drawable.album32, "Love", "Last", Months.JUL),
    SingerData(R.drawable.album33, "울린", "Anxious", Months.JUL),
    SingerData(R.drawable.album34, "최현상", "Love", Months.JUL),
    SingerData(R.drawable.album11, "Prelude", "Yet", Months.JUL),
    SingerData(R.drawable.album12, "1844", "Face", Months.AUG),
    SingerData(R.drawable.album13, "OST", "Saturn", Months.AUG),
    SingerData(R.drawable.album14, "한승희", "Other", Months.AUG),
    SingerData(R.drawable.album15, "숨", "Crystalline", Months.AUG),
    SingerData(R.drawable.album16, "캐나비", "Just", Months.AUG),
    SingerData(R.drawable.album17, "is", "Pilgrim", Months.SEP),
    SingerData(R.drawable.album18, "Dopein", "A", Months.SEP),
    SingerData(R.drawable.album19, "and", "오등", Months.SEP),
    SingerData(R.drawable.album20, "twodollar", "영이야", Months.SEP),
    SingerData(R.drawable.album21, "예쁜날", "이", Months.OCT),
    SingerData(R.drawable.album22, "달리", "BVNDIT", Months.OCT),
    SingerData(R.drawable.album25, "흔적", "Airman", Months.OCT),
    SingerData(R.drawable.album26, "남현", "우린", Months.NOV),
    SingerData(R.drawable.album27, "Good", "노들뮤직", Months.NOV),
    SingerData(R.drawable.album28, "고갱", "Color", Months.NOV),
    SingerData(R.drawable.album29, "날", "델피늄", Months.NOV),
    SingerData(R.drawable.album30, "Ways", "Let", Months.NOV),
    SingerData(R.drawable.album31, "둘이", "If", Months.DEC),
    SingerData(R.drawable.album32, "황평안", "yours", Months.DEC),
    SingerData(R.drawable.album33, "Price", "THEY", Months.DEC),
    SingerData(R.drawable.album34, "TIGRIX", "알면서도", Months.DEC)
)