wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.14.0
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.9.13
    start_time: 1686991326.631884
    t:
      1:
      - 55
      3:
      - 23
      4: 3.9.13
      5: 0.14.0
      8:
      - 1
      - 5
