# Generated by Django 2.1 on 2018-08-17 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('relocations', '0003_delete_contents'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_name', models.CharField(max_length=100)),
                ('content_file', models.FileField(upload_to='uploads/')),
                ('content_author', models.CharField(max_length=50)),
            ],
        ),
    ]
