# Generated by Django 2.1 on 2018-08-20 03:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('relocations', '0004_contents'),
    ]

    operations = [
        migrations.AddField(
            model_name='contents',
            name='upload_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 20, 3, 27, 24, 256256, tzinfo=utc), verbose_name='upload date'),
        ),
        migrations.AlterField(
            model_name='contents',
            name='content_author',
            field=models.CharField(default='anonymous', max_length=50),
        ),
        migrations.AlterField(
            model_name='contents',
            name='content_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
