# Generated by Django 2.1 on 2018-08-21 07:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('relocations', '0006_auto_20180820_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contents',
            name='upload_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 21, 7, 4, 28, 40733, tzinfo=utc), verbose_name='upload date'),
        ),
    ]
