# Generated by Django 2.1 on 2018-08-17 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relocations', '0002_auto_20180817_1535'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contents',
        ),
    ]
