# Generated by Django 2.1 on 2018-08-20 07:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('relocations', '0005_auto_20180820_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='contents',
            name='counts',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='contents',
            name='upload_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 20, 7, 27, 24, 279022, tzinfo=utc), verbose_name='upload date'),
        ),
    ]
