# Generated by Django 2.1 on 2018-09-03 06:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('relocations', '0009_auto_20180823_1740'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadFile',
        ),
        migrations.AddField(
            model_name='contents',
            name='status',
            field=models.CharField(default='uploaded', max_length=10),
        ),
        migrations.AlterField(
            model_name='contents',
            name='file',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='contents',
            name='upload_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 3, 6, 0, 9, 499355, tzinfo=utc), verbose_name='upload date'),
        ),
    ]
