# Generated by Django 2.1 on 2018-09-03 06:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('relocations', '0010_auto_20180903_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contents',
            name='upload_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 3, 6, 1, 5, 793909, tzinfo=utc), verbose_name='upload date'),
        ),
    ]
